name: Porfolio Site Build

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
